import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen min-h-screen bg-amber-50 relative overflow-x-hidden flex  justify-center`}
      >
        {children}
        <div className='absolute inset-0 -z-10 w-fill h-full'>
          <div className='absolute top-5 left-5 w-8 h-8 bg-amber-200 rounded-full opacity-50 animate-pulse' />
          <div className='absolute bottom-5 right-5 w-12 h-12 bg-amber-200 rounded-full opacity-50 animate-pulse' />
        </div>
      </body>
    </html>
  );
}
